-- Constraints 

-- Private keys

ALTER TABLE DELIVERY_OPTIONS
ADD CONSTRAINT PK_Delivery_Options PRIMARY KEY (ID);

ALTER TABLE MENU_CATEGORY
ADD CONSTRAINT PK_Menu_Category PRIMARY KEY (ID);

ALTER TABLE CUISINES
ADD CONSTRAINT PK_Cuisines PRIMARY KEY (ID);

ALTER TABLE COUNTRY
ADD CONSTRAINT PK_Country PRIMARY KEY (ID);

ALTER TABLE STATE
ADD CONSTRAINT PK_State PRIMARY KEY (ID);

ALTER TABLE SIGNUP
ADD CONSTRAINT PK_Signup PRIMARY KEY (ID);

ALTER TABLE RESTURANT
ADD CONSTRAINT PK_Resturant PRIMARY KEY (ID);

ALTER TABLE DELIVERY_TYPE_RESTURANT_MAPPINGS
ADD CONSTRAINT PK_Delivery_Type_Resturant_Mapping PRIMARY KEY (Delivery_ID,Resturant_ID);

ALTER TABLE APPETIZER
ADD CONSTRAINT PK_Appetizer PRIMARY KEY (ID);

ALTER TABLE SALADS
ADD CONSTRAINT PK_Salads PRIMARY KEY (ID);

ALTER TABLE DESSERTS
ADD CONSTRAINT PK_Desserts PRIMARY KEY (ID);

ALTER TABLE BEVERAGES
ADD CONSTRAINT PK_Beverages PRIMARY KEY (ID);

ALTER TABLE MAIN_COURSE
ADD CONSTRAINT PK_Main_Course PRIMARY KEY (ID);

ALTER TABLE REVIEWS
ADD CONSTRAINT PK_Reviews PRIMARY KEY (ID);

ALTER TABLE ORDERS
ADD CONSTRAINT PK_Orders PRIMARY KEY (ID);

ALTER TABLE EVENTS
ADD CONSTRAINT PK_Events PRIMARY KEY (ID);

ALTER TABLE REGISTERATION
ADD CONSTRAINT PK_Registeration PRIMARY KEY (Event_ID,Customer_ID);

ALTER TABLE CUSTOMER
ADD CONSTRAINT PK_Customer PRIMARY KEY (ID);

-- ALTER TABLE SocialMedia
-- ADD CONSTRAINT PK_Social_Media PRIMARY KEY (Customer_ID,Media_Type);
-- 
ALTER TABLE FAVOURITES
ADD CONSTRAINT PK_Favourites PRIMARY KEY (Customer_ID,Resturant_ID);


-- Autoincrement constraint added



