DROP DATABASE IF EXISTS Yelp_Prototype;

CREATE DATABASE Yelp_Prototype;

USE Yelp_Prototype;


-- STATIC TABLES -> Tables populated only by Admin, mostly through sql scripts

CREATE TABLE DELIVERY_OPTIONS
(
ID INT NOT NULL,
Options VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE MENU_CATEGORY
(
ID INT NOT NULL,
Category VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE CUISINES
(
ID INT NOT NULL,
Category VARCHAR(50) NOT NULL UNIQUE
);



-- Tables To be Updated from Backend
CREATE TABLE SIGNUP
(
ID INT NOT NULL,
Email VARCHAR(50) NOT NULL UNIQUE,
Password VARCHAR(20) NOT NULL,
Persona	ENUM('Customer','Resturant') NOT NULL
);


CREATE TABLE RESTURANT
(
ID INT NOT NULL,
Resturant_ID INT NOT NULL,
Name VARCHAR(50) NOT NULL UNIQUE,
Country_ID BIGINT NOT NULL,
State_ID BIGINT NOT NULL,
City VARCHAR(25) NOT NULL,
Zip INT NOT NULL CHECK (Zip BETWEEN 10000 and 99999),
Street VARCHAR(50) NOT NULL,
Phone_no BIGINT NOT NULL CHECK (Phone_no BETWEEN 1000000000 and 9999999999),
Country_Code INT NOT NULL,
Opening_Time TIME NOT NULL,
Closing_Time TIME NOT NULL,
ImageURL VARCHAR(100)
);


CREATE TABLE DELIVERY_TYPE_RESTURANT_MAPPINGS
(
Delivery_ID INT NOT NULL,
Resturant_ID VARCHAR(50) NOT NULL UNIQUE
);




