DROP DATABASE IF EXISTS Yelp_Prototype;

CREATE DATABASE Yelp_Prototype;

USE Yelp_Prototype;


-- STATIC TABLES -> Tables populated only by Admin, mostly through sql scripts

CREATE TABLE DELIVERY_OPTIONS
(
ID INT NOT NULL,
Options VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE MENU_CATEGORY
(
ID INT NOT NULL,
Category VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE CUISINES
(
ID INT NOT NULL,
Category VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE COUNTRY(
ID INT NOT NULL,
Name VARCHAR(50) NOT NULL UNIQUE,
Country_Code INT NOT NULL UNIQUE
);

CREATE TABLE STATE(
ID INT NOT NULL,
Name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE DELIVERY_STATUS(
ID INT NOT NULL,
Status VARCHAR(50) NOT NULL UNIQUE
); 

 



-- Tables To be Updated from Backend
CREATE TABLE SIGNUP
(
ID INT NOT NULL,
Email VARCHAR(50) NOT NULL UNIQUE,
Password VARCHAR(20) NOT NULL,
Persona	ENUM('Customer','Resturant') NOT NULL
);


CREATE TABLE RESTURANT
(
ID INT NOT NULL,
Resturant_ID INT NOT NULL UNIQUE,
Name VARCHAR(50) NOT NULL UNIQUE,
Country_ID INT NOT NULL,
State_ID INT NOT NULL,
City VARCHAR(25) NOT NULL,
Zip INT NOT NULL CHECK (Zip BETWEEN 10000 and 99999),
Street VARCHAR(50) NOT NULL,
Phone_no BIGINT NOT NULL UNIQUE CHECK (Phone_no BETWEEN 1000000000 and 9999999999) ,
Country_Code INT NOT NULL,
Opening_Time TIME NOT NULL,
Closing_Time TIME NOT NULL,
ImageURL VARCHAR(100)
);


CREATE TABLE DELIVERY_TYPE_RESTURANT_MAPPINGS
(
Delivery_ID INT NOT NULL,
Resturant_ID INT NOT NULL
);

CREATE TABLE APPETIZER(
ID INT NOT NULL,
Resturant_ID INT NOT NULL,
Name VARCHAR(50) NOT NULL,
Main_Ingredients VARCHAR(100) NOT NULL,
Price DECIMAL(4,2) NOT NULL,
Cuisine_ID INT NOT NULL,
Description VARCHAR(100),
Image_URL VARCHAR(100)
);

CREATE TABLE SALADS(
ID INT NOT NULL,
Resturant_ID INT NOT NULL,
Name VARCHAR(50) NOT NULL,
Main_Ingredients VARCHAR(100) NOT NULL,
Price DECIMAL(4,2) NOT NULL,
Cuisine_ID INT NOT NULL,
Description VARCHAR(100),
Image_URL VARCHAR(100)
);

CREATE TABLE DESSERTS(
ID INT NOT NULL,
Resturant_ID INT NOT NULL,
Name VARCHAR(50) NOT NULL,
Main_Ingredients VARCHAR(100) NOT NULL,
Price DECIMAL(4,2) NOT NULL,
Cuisine_ID INT NOT NULL,
Description VARCHAR(100),
Image_URL VARCHAR(100)
);

CREATE TABLE BEVERAGES(
ID INT NOT NULL,
Resturant_ID INT NOT NULL,
Name VARCHAR(50) NOT NULL,
Main_Ingredients VARCHAR(100) NOT NULL,
Price DECIMAL(4,2) NOT NULL,
Cuisine_ID INT NOT NULL,
Description VARCHAR(100),
Image_URL VARCHAR(100)
);

CREATE TABLE MAIN_COURSE(
ID INT NOT NULL,
Resturant_ID INT NOT NULL,
Name VARCHAR(50) NOT NULL,
Main_Ingredients VARCHAR(100) NOT NULL,
Price DECIMAL(4,2) NOT NULL,
Cuisine_ID INT NOT NULL,
Description VARCHAR(100),
Image_URL VARCHAR(100)
);

CREATE TABLE REVIEWS(
ID INT NOT NULL,
Rating INT NOT NULL CHECK (Rating BETWEEN 1 and 5),
Resturant_ID INT NOT NULL,
Customer_ID INT NOT NULL,
Date DATE NOT NULL
);

CREATE TABLE ORDERS(
ID INT NOT NULL,
Resturant_ID INT NOT NULL,
Customer_ID INT NOT NULL,
Date DATE NOT NULL,
Time TIME NOT NULL,
Order_Type ENUM('Delivery','Pick_up') NOT NULL,
Delivery_Status INT NOT NULL,
Order_Status ENUM('New Order','Delivered Order','Cancelled Order') NOT NULL,
Ordered_Dishes VARCHAR(1000) NOT NULL,
Bill DECIMAL(5,2) NOT NULL
);

CREATE TABLE EVENTS
(
ID INT NOT NULL,
Name VARCHAR(100) NOT NULL UNIQUE,
Resturant_ID INT NOT NULL,
Description VARCHAR(100) NOT NULL,
Date DATE NOT NULL,
Time TIME NOT NULL,
Country_ID INT NOT NULL,
State_ID INT NOT NULL,
City VARCHAR(25) NOT NULL,
Zip INT NOT NULL CHECK (Zip BETWEEN 10000 and 99999),
Street VARCHAR(50) NOT NULL,
Hashtags VARCHAR(100)
);

CREATE TABLE REGISTERATION(
Event_ID INT NOT NULL,
Customer_ID INT NOT NULL
);

CREATE TABLE CUSTOMER
(
ID INT NOT NULL,
Customer_ID INT NOT NULL UNIQUE,
Name VARCHAR(50) NOT NULL,
Nick_Name VARCHAR(50) NOT NULL,
Date_Of_Birth DATE,
Country_ID INT NOT NULL,
State_ID INT NOT NULL,
City VARCHAR(25) NOT NULL,
Zip INT NOT NULL CHECK (Zip BETWEEN 10000 and 99999),
Street VARCHAR(50) NOT NULL,
Phone_no BIGINT NOT NULL CHECK (Phone_no BETWEEN 1000000000 and 9999999999),
Country_Code INT NOT NULL,
Headline VARCHAR(100),
I_Love VARCHAR(100) ,
Find_Me_In VARCHAR(100),
Join_Date DATE NOT NULL,
Website VARCHAR(100),
ImageURL VARCHAR(100)
);

-- CREATE TABLE SocialMedia(
-- Customer_ID INT NOT NULL,
-- Media_Type	ENUM('Facebook','Instagram','Quora','Twitter') NOT NULL,
-- URL VARCHAR(100) NOT NULL
-- );

CREATE TABLE FAVOURITES(
Customer_ID INT NOT NULL,
Resturant_ID INT NOT NULL
);










