INSERT INTO DELIVERY_OPTIONS(Options) VALUES ('Curbside Pickup');
INSERT INTO DELIVERY_OPTIONS(Options) VALUES ('Dine In');
INSERT INTO DELIVERY_OPTIONS(Options) VALUES ('Yelp Delivery');


INSERT INTO MENU_CATEGORY(Category) VALUES ('APPETIZER');
INSERT INTO MENU_CATEGORY(Category) VALUES ('SALADS');
INSERT INTO MENU_CATEGORY(Category) VALUES ('DESSERTS');
INSERT INTO MENU_CATEGORY(Category) VALUES ('BEVERAGES');
INSERT INTO MENU_CATEGORY(Category) VALUES ('MAIN_COURSE');


INSERT INTO CUISINES(Category) VALUES ('Indian');
INSERT INTO CUISINES(Category) VALUES ('Chinese');
INSERT INTO CUISINES(Category) VALUES ('Mexican');
INSERT INTO CUISINES(Category) VALUES ('Italian');
INSERT INTO CUISINES(Category) VALUES ('Japanese');
INSERT INTO CUISINES(Category) VALUES ('Greek');
INSERT INTO CUISINES(Category) VALUES ('French');
INSERT INTO CUISINES(Category) VALUES ('Thai');
INSERT INTO CUISINES(Category) VALUES ('Spanish');
INSERT INTO CUISINES(Category) VALUES ('Mediterranean');



INSERT INTO COUNTRY(Name,Country_Code) VALUES ('U.S.A',1);



INSERT INTO STATE(Name) VALUES ('Alabama');
INSERT INTO STATE(Name) VALUES ('Alaska');
INSERT INTO STATE(Name) VALUES ('Arizona');
INSERT INTO STATE(Name) VALUES ('Arkansas');
INSERT INTO STATE(Name) VALUES ('California');
INSERT INTO STATE(Name) VALUES ('Colorado');
INSERT INTO STATE(Name) VALUES ('Connecticut');
INSERT INTO STATE(Name) VALUES ('Delaware');
INSERT INTO STATE(Name) VALUES ('Florida');
INSERT INTO STATE(Name) VALUES ('Georgia');
INSERT INTO STATE(Name) VALUES ('Hawaii');
INSERT INTO STATE(Name) VALUES ('Idaho');
INSERT INTO STATE(Name) VALUES ('Illinois');
INSERT INTO STATE(Name) VALUES ('Indiana');
INSERT INTO STATE(Name) VALUES ('Iowa');
INSERT INTO STATE(Name) VALUES ('Kansas');
INSERT INTO STATE(Name) VALUES ('Kentucky');
INSERT INTO STATE(Name) VALUES ('Louisiana');
INSERT INTO STATE(Name) VALUES ('Maine');
INSERT INTO STATE(Name) VALUES ('Maryland');
INSERT INTO STATE(Name) VALUES ('Massachusetts');
INSERT INTO STATE(Name) VALUES ('Michigan');
INSERT INTO STATE(Name) VALUES ('Minnesota');
INSERT INTO STATE(Name) VALUES ('Mississippi');
INSERT INTO STATE(Name) VALUES ('Missouri');
INSERT INTO STATE(Name) VALUES ('Montana');
INSERT INTO STATE(Name) VALUES ('Nebraska');
INSERT INTO STATE(Name) VALUES ('Nevada');
INSERT INTO STATE(Name) VALUES ('New Hampshire');
INSERT INTO STATE(Name) VALUES ('New Jersey');
INSERT INTO STATE(Name) VALUES ('New Mexico');
INSERT INTO STATE(Name) VALUES ('New York');
INSERT INTO STATE(Name) VALUES ('North Carolina');
INSERT INTO STATE(Name) VALUES ('North Dakota');
INSERT INTO STATE(Name) VALUES ('Ohio');
INSERT INTO STATE(Name) VALUES ('Oklahoma');
INSERT INTO STATE(Name) VALUES ('Oregon');
INSERT INTO STATE(Name) VALUES ('Pennsylvania');
INSERT INTO STATE(Name) VALUES ('Rhode Island');
INSERT INTO STATE(Name) VALUES ('South Carolina');
INSERT INTO STATE(Name) VALUES ('South Dakota');
INSERT INTO STATE(Name) VALUES ('Tennessee');
INSERT INTO STATE(Name) VALUES ('Texas');
INSERT INTO STATE(Name) VALUES ('Utah');
INSERT INTO STATE(Name) VALUES ('Vermont');
INSERT INTO STATE(Name) VALUES ('Virginia');
INSERT INTO STATE(Name) VALUES ('Washington');
INSERT INTO STATE(Name) VALUES ('West Virginia');
INSERT INTO STATE(Name) VALUES ('Wisconsin');
INSERT INTO STATE(Name) VALUES ('Wyoming');



INSERT INTO DELIVERY_STATUS(Status) VALUES ('Order Received');
INSERT INTO DELIVERY_STATUS(Status) VALUES ('Preparing');
INSERT INTO DELIVERY_STATUS(Status) VALUES ('On the way');
INSERT INTO DELIVERY_STATUS(Status) VALUES ('Delivered');
INSERT INTO DELIVERY_STATUS(Status) VALUES ('Pick up Ready');
INSERT INTO DELIVERY_STATUS(Status) VALUES ('Picked up');


INSERT INTO GENDER_LIST(Gender) VALUES ('Male');
INSERT INTO GENDER_LIST(Gender) VALUES ('Female');
INSERT INTO GENDER_LIST(Gender) VALUES ('Other');
